name: Secure Connection Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Direct DNSCrypt Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y dnscrypt-proxy openvpn
          sudo sed -i 's/^listen_addresses.*/listen_addresses = ['\''127.0.0.1:5353'\'']/' /etc/dnscrypt-proxy/dnscrypt-proxy.toml
          sudo dnscrypt-proxy -config /etc/dnscrypt-proxy/dnscrypt-proxy.toml &
          sleep 5
          echo "nameserver 127.0.0.1" | sudo tee /etc/resolv.conf
          
      - name: Test DNS
        run: dig @127.0.0.1 -p 5353 google.com
        
      - name: Try VPN Connection
        run: |
          # استخدام خادم VPN عام للاختبار
          curl -s https://www.vpngate.net/api/iphone/ | grep -E "^#" -v | head -1 > vpn_info.csv
          echo "Attempting VPN connection..."
          sudo openvpn --config <(echo "$(python3 -c "import base64, sys; print(base64.b64decode(open('vpn_info.csv').read().split(',')[14]).decode())")") &
          sleep 10
          ip addr show
