name: Build and Run Docker

on:
  push:
    branches:
      - main  # يمكنك تغييره حسب اسم فرعك

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t secure-connection .

      - name: Run Docker container
        run: |
          docker run --rm --privileged --cap-add=NET_ADMIN --cap-add=SYS_ADMIN secure-connection