name: Build and Test Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx with cache
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image with cache
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            --load \
            -t secure-connection .

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Test Docker image build
        run: |
          docker images secure-connection

      - name: Test basic container functionality
        run: |
          echo "Testing container basic functionality..."
          docker run --rm secure-connection python3 --version

      - name: Test network connectivity in container
        run: |
          echo "Testing network connectivity..."
          docker run --rm --network=host secure-connection ping -c 3 8.8.8.8 || true

      - name: Test DNS resolution in container
        run: |
          echo "Testing DNS resolution..."
          docker run --rm --network=host secure-connection nslookup google.com || true

      - name: Run status check only (safe mode)
        run: |
          echo "Running status check in safe mode..."
          docker run --rm --network=host \
            -e TEST_MODE=true \
            secure-connection python3 main.py --status-only || true

      - name: Test environment check script
        run: |
          echo "Testing environment check..."
          docker run --rm secure-connection python3 check_environment.py || true

      # This step will only run if we're not in GitHub Actions (commented out for safety)
      # - name: Run full setup (requires privileged mode)
      #   run: |
      #     echo "⚠️  Full setup requires privileged access - skipping in CI"
      #     echo "To run full setup locally, use:"
      #     echo "docker run --privileged --cap-add=NET_ADMIN --cap-add=SYS_ADMIN -it secure-connection"